
import { Language, Translation } from './types';

export const TRANSLATIONS: Record<Language, Translation> = {
  ar: {
    title: "منصة حلل حسابك الاستراتيجية",
    subtitle: "فك شفرة خوارزميات السوشيال ميديا وحوّل حسابك من حالة الركود إلى النمو الانفجاري عبر تحليل تقني عميق.",
    placeholder: "أدخل اسم المستخدم (مثال: yaz.salaq) أو رابط الملف الشخصي...",
    analyzeBtn: "بدء التدقيق الفني الشامل",
    platformLabel: "نظام التحليل المستهدف:",
    followToUnlock: "يرجى متابعة حسابي الرسمي في انستقرام لفك تشفير بيانات الموقع وفتح أدوات التحليل المتقدمة",
    followBtn: "متابعة Yaz Salaq لفتح النظام",
    unlocked: "تم التحقق - الدخول متاح الآن",
    cookieTitle: "بروتوكول البيانات المحلية",
    cookieMsg: "نستخدم تقنيات التخزين الذكي لضمان استمرارية جلسة التحليل الخاصة بك وحفظ سجل تقاريرك.",
    cookieAutoAccept: "الموافقة التلقائية خلال",
    resultsTitle: "تقرير التدقيق الاستراتيجي الشامل",
    problemLabel: "الثغرات الخوارزمية المكتشفة:",
    solutionLabel: "خارطة طريق النمو المقترحة:",
    copyright: "جميع الحقوق محفوظة للمطور ياز سلاق - خبير نمو المنصات الرقمية",
    errorMsg: "فشل النظام في استرداد البيانات. يرجى التأكد من صحة الحساب والمحاولة مرة أخرى.",
    loading: "جاري تحليل أنماط التفاعل وفك شفرة الخوارزمية الخاصة بك...",
    historyTitle: "أرشيف التقارير السابقة",
    noHistory: "لا يوجد سجل تحليلات محفوظ حالياً.",
    clearHistory: "مسح الأرشيف",
    viewHistory: "عرض السجل",
    reelsLabel: "مقاطع الريلز (Reels)",
    facebookLabel: "صفحات الفيسبوك",
    instagramAccount: "تدقيق الحساب الشخصي",
    instagramReels: "تحليل استراتيجية الريلز"
  },
  en: {
    title: "Strategic Audit Platform",
    subtitle: "Decode social media algorithms and transition your account from stagnation to explosive growth with deep technical diagnostics.",
    placeholder: "Enter username (e.g., yaz.salaq) or profile link...",
    analyzeBtn: "Execute Comprehensive Technical Audit",
    platformLabel: "Targeted Diagnostic System:",
    followToUnlock: "Please follow my official Instagram to decrypt site data and unlock advanced growth frameworks",
    followBtn: "Follow Yaz Salaq to Unlock",
    unlocked: "Verification Success - System Accessible",
    cookieTitle: "Local Data Protocol",
    cookieMsg: "We utilize smart storage technology to maintain your analysis session and preserve your report history.",
    cookieAutoAccept: "Auto-Accepting in",
    resultsTitle: "Strategic Audit Comprehensive Report",
    problemLabel: "Identified Algorithmic Gaps:",
    solutionLabel: "Proposed Growth Roadmap:",
    copyright: "All rights reserved to Yaz Salaq - Digital Growth Strategy Expert",
    errorMsg: "System failed to retrieve data. Please verify the account credentials and retry.",
    loading: "Analyzing engagement patterns and decoding your unique algorithm...",
    historyTitle: "Previous Audit Archives",
    noHistory: "No audit reports saved yet.",
    clearHistory: "Reset Archives",
    viewHistory: "View History",
    reelsLabel: "Instagram Reels",
    facebookLabel: "Facebook Pages",
    instagramAccount: "Profile Audit",
    instagramReels: "Reels Content Diagnostics"
  },
  he: {
    title: "פלטפורמת ביקורת אסטרטגית",
    subtitle: "פענח את אלגוריתמי המדיה החברתית והעבר את החשבון שלך מקיפאון לצמיחה מהירה בעזרת אבחון טכני עמוק.",
    placeholder: "הזן שם משתמש (למשל: yaz.salaq) או קישור לפרופיל...",
    analyzeBtn: "בצע ביקורת טכנית מקיפה",
    platformLabel: "מערכת אבחון ממוקדת:",
    followToUnlock: "אנא עקוב אחר האינסטגרם הרשמי שלי כדי לפענח את נתוני האתר ולפתוח כלי ניתוח מתקדמים",
    followBtn: "עקוב אחרי Yaz Salaq לפתיחה",
    unlocked: "אימות הצליח - המערכת נגישה",
    cookieTitle: "פרוטוקול נתונים מקומי",
    cookieMsg: "אנו משתמשים בטכנולוגיית אחסון חכמה כדי לשמור על מפגש הניתוח שלך ועל היסטוריית הדוחות.",
    cookieAutoAccept: "אישור אוטומטי בעוד",
    resultsTitle: "דו\"ח ביקורת אסטרטגי מקיף",
    problemLabel: "פערים אלגוריתמיים שזוהו:",
    solutionLabel: "מפת דרכים מוצעת לצמיחה:",
    copyright: "כל הזכויות שמורות ליאז סלאק - מומחה לאסטרטגיית צמיחה דיגיטלית",
    errorMsg: "המערכת נכשלה באחזור הנתונים. אנא בדוק את פרטי החשבון ונסה שוב.",
    loading: "מנתח דפוסי מעורבות ומפענח את האלגוריתם שלך...",
    historyTitle: "ארכיון דוחות קודמים",
    noHistory: "אין עדיין דוחות שמורים.",
    clearHistory: "אפס ארכיון",
    viewHistory: "צפה בהיסטוריה",
    reelsLabel: "אינסטגרם רילס",
    facebookLabel: "דפי פייסבוק",
    instagramAccount: "ביקורת פרופיל",
    instagramReels: "אבחון תוכן רילס"
  }
};
