
import { Language, Translation } from './types';

export const TRANSLATIONS: Record<Language, Translation> = {
  ar: {
    title: "حلل حسابك",
    subtitle: "اكتشف لماذا لا ينمو حسابك على انستقرام وتيك توك من خلال تحليل ذكي وشامل.",
    placeholder: "ادخل اسم المستخدم أو رابط الحساب هنا...",
    analyzeBtn: "ابدأ التحليل الآن",
    platformLabel: "اختر المنصة:",
    followToUnlock: "يرجى متابعة حسابي في انستقرام لفك قفل الموقع",
    followBtn: "متابعة Yaz Salaq",
    unlocked: "تم فك القفل بنجاح!",
    cookieTitle: "ملفات تعريف الارتباط",
    cookieMsg: "نستخدم الكوكيز لتحسين تجربتك.",
    cookieAutoAccept: "قبول خلال",
    resultsTitle: "نتائج التحليل",
    problemLabel: "المشاكل المكتشفة:",
    solutionLabel: "الحلول المقترحة:",
    copyright: "جميع الحقوق محفوظة لصانع الموقع ياز سلاق",
    errorMsg: "حدث خطأ ما. يرجى التأكد من البيانات والمحاولة مرة أخرى.",
    loading: "جاري تحليل البيانات بذكاء...",
    historyTitle: "سجل التحليلات",
    noHistory: "لا يوجد سجل تحليلات بعد.",
    clearHistory: "مسح السجل",
    viewHistory: "عرض السجل",
    reelsLabel: "ريلز انستقرام",
    facebookLabel: "فيسبوك",
    instagramAccount: "تحليل الحساب",
    instagramReels: "تحليل الريلز"
  },
  en: {
    title: "Analyze Your Account",
    subtitle: "Discover why your Instagram and TikTok accounts aren't growing with smart, comprehensive analysis.",
    placeholder: "Enter username or profile link...",
    analyzeBtn: "Start Analysis",
    platformLabel: "Select Platform:",
    followToUnlock: "Please follow my Instagram to unlock the site",
    followBtn: "Follow Yaz Salaq",
    unlocked: "Unlocked successfully!",
    cookieTitle: "Cookies",
    cookieMsg: "We use cookies to enhance your experience.",
    cookieAutoAccept: "Accepting in",
    resultsTitle: "Analysis Results",
    problemLabel: "Detected Problems:",
    solutionLabel: "Suggested Solutions:",
    copyright: "All rights reserved to Yaz Salaq",
    errorMsg: "Something went wrong. Please check the data and try again.",
    loading: "Smartly analyzing data...",
    historyTitle: "Analysis History",
    noHistory: "No analysis history yet.",
    clearHistory: "Clear History",
    viewHistory: "View History",
    reelsLabel: "Instagram Reels",
    facebookLabel: "Facebook",
    instagramAccount: "Account Analysis",
    instagramReels: "Reels Analysis"
  },
  he: {
    title: "נתח את החשבון שלך",
    subtitle: "גלה מדוע חשבונות האינסטגרם והטיקטוק שלך לא צומחים בעזרת ניתוח חכם ומקיף.",
    placeholder: "הזן שם משתמש או קישור לפרופיל...",
    analyzeBtn: "התחל ניתוח",
    platformLabel: "בחר פלטפורמה:",
    followToUnlock: "אנא עקוב אחר האינסטגרם שלי כדי לפתוח את האתר",
    followBtn: "עקוב אחרי Yaz Salaq",
    unlocked: "נפתח בהצלחה!",
    cookieTitle: "עוגיות",
    cookieMsg: "אנו משתמשים בעוגיות לשיפור החוויה.",
    cookieAutoAccept: "אישור בעוד",
    resultsTitle: "תוצאות ניתוח",
    problemLabel: "בעיות שזוהו:",
    solutionLabel: "פתרונות מוצעים:",
    copyright: "כל הזכויות שמורות ליאז סלאק",
    errorMsg: "משהו השתבש. אנא בדוק את הנתונים ונסה שוב.",
    loading: "מנתח נתונים בחוכמה...",
    historyTitle: "היסטוריית ניתוחים",
    noHistory: "אין עדיין היסטוריית ניתוחים.",
    clearHistory: "נקה היסטוריה",
    viewHistory: "צפה בהיסטוריה",
    reelsLabel: "אינסטגרם רילס",
    facebookLabel: "פייסבוק",
    instagramAccount: "ניתוח חשבון",
    instagramReels: "ניתוח רילס"
  }
};
